{
	"Popup Simple": {
		"scope": "html",
		"prefix": "popupsimpl",
		"body": [
			"<div id=\"popup\" class=\"popup\">",
			"  <div class=\"popup__area\"></div>",
			"  <div class=\"popup__body\">",
			"    <div class=\"popup__content\">",
			"      <div class=\"popup__close\"></div>",
			"      <div class=\"popup__title\"></div>",
			"      <div class=\"popup__text\"></div>",
			"      <div class=\"popup__img\"></div>",
			"    </div>",
			"  </div>",
			"</div>"
		],
		"description": "added simple popup"
	}
}

{
	"Popup with Form": {
		"scope": "html",
		"prefix": "popupform",
		"body": [
			"<div id=\"popup\" class=\"popup\">",
			"  <div class=\"popup__area\"></div>",
			"  <div class=\"popup__body\">",
			"    <div class=\"popup__content\">",
			"      <div class=\"popup__title\">Login</div>",
			"      <form>",
			"        <label class=\"popup__label-name\">",
			"          <input type=\"text\" placeholder=\"Name\" required>",
			"        </label>",
			"        <label class=\"popup__label-pass\">",
			"          <input type=\"text\" placeholder=\"Password\" required>",
			"        </label>",
			"        <button class=\"popup__btn\" type=\"submit\">submit</button>",
			"        <a class=\"popup__account\" href=\"#\">Creat An Account</a>",
			"        <a class=\"popup__password\" href=\"#\">Lost password?</a>",
			"      </form>",
			"    </div>",
			"  </div>",
			"</div>"
		],
		"description": "added popup with form"
	}
}


{
	"CSS to Popup": {
		"scope": "css, scss",
		"prefix": "csspopup",
		"body": [
			".popup {",
			"  position: fixed;",
			"  width: 100%;",
			"  height: 100%;",
			"  background-color: rgba(32, 38, 50, 0.8);",
			"  top: 0;",
			"  left: 0;",
			"  opacity: 0;",
			"  visibility: hidden;",
			"  overflow-y: auto;",
			"  overflow-x: hidden;",
			"  transition: all 0.3s;",
			"  z-index: -10;",
			"}",
			".popup.opened {",
			"  opacity: 1;",
			"  visibility: visible;",
			"  z-index: 1000;",
			"  transition: all 0.4s ease-in-out;",
			"}",
			".popup.opened .popup__content {",
			"  transform: translate(0px, 0%);",
			"  opacity: 1;",
			"}",
			".popup__area {",
			"  position: absolute;",
			"  width: 100%;",
			"  height: 100%;",
			"  top: 0;",
			"  left: 0;",
			"  z-index: 0;",
			"}",
			".popup__body {",
			"  min-height: 100%;",
			"  display: flex;",
			"  justify-content: center;",
			"  align-items: center;",
			"  padding: 30px 10px;",
			"}",
			".popup__content {",
			"  background-color: #fff;",
			"  color: #000;",
			"  color: #303b4d;",
			"  max-width: 880px;",
			"  border-radius: 10px;",
			"  border: 1px solid rgb(222, 225, 231);",
			"  border-top: 6px solid #2399f1;",
			"  padding: 45px 65px 35px;",
			"  position: relative;",
			"  transition: all 0.5s;",
			"  opacity: 0;",
			"  transform: translate(0px, -100%);",
			"}",
			".popup__close {",
			"  position: absolute;",
			"  top: 15px;",
			"  right: 15px;",
			"  cursor: pointer;",
			"  width: 10px;",
			"  padding: 12px;",
			"}",
			".popup__close::before,",
			".popup__close::after {",
			"  position: absolute;",
			"  content: \"\";",
			"  width: 22px;",
			"  height: 2px;",
			"  right: 1px;",
			"  background-color: #000;",
			"}",
			".popup__close::before {",
			"  transform: rotate(45deg);",
			"}",
			".popup__close::after {",
			"  transform: rotate(-45deg);",
			"}"
		],
		"description": "all css to myOwnPopup"
	}
}

